package Java101;

public class findTheDifference {
    //You are given two strings s and t.
    //
    //String t is generated by random shuffling string s and then add one more letter at a random position.
    //
    //Return the letter that was added to t.
    public char findTheDifference(String s, String t) {
        int a=0;
        for(char b : t.toCharArray()) {
            a+=b;
        }
        for(char b: s.toCharArray()){
            a-=b;
        }
        return(char) a;

    }
}
